/* Generated by Yosys 0.10+12 (git sha1 UNKNOWN, gcc 10.1.0 -fPIC -Os) */

(* top =  1  *)
(* src = "./verilog/b10_C.v:1.1-177.10" *)
module b10_C(R_BUTTON, G_BUTTON, KEY, START, TEST, RTS, RTR, VOTO0_REG_SCAN_IN, V_IN_3_, V_IN_2_, V_IN_1_, V_IN_0_, STATO_REG_3__SCAN_IN, STATO_REG_2__SCAN_IN, STATO_REG_1__SCAN_IN, STATO_REG_0__SCAN_IN, V_OUT_REG_3__SCAN_IN, V_OUT_REG_2__SCAN_IN, V_OUT_REG_1__SCAN_IN, V_OUT_REG_0__SCAN_IN, SIGN_REG_3__SCAN_IN, VOTO1_REG_SCAN_IN, CTR_REG_SCAN_IN, VOTO3_REG_SCAN_IN, LAST_R_REG_SCAN_IN, CTS_REG_SCAN_IN, VOTO2_REG_SCAN_IN, LAST_G_REG_SCAN_IN, U207, U208, U209, U210, U211, U212, U233, U234, U235, U236, U237, U238, U239, U240, U241, U242, U243);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  (* src = "./verilog/b10_C.v:2.326-2.341" *)
  wire _132_;
  (* src = "./verilog/b10_C.v:2.382-2.397" *)
  wire _133_;
  (* src = "./verilog/b10_C.v:2.17-2.25" *)
  wire _134_;
  (* src = "./verilog/b10_C.v:2.27-2.30" *)
  wire _135_;
  (* src = "./verilog/b10_C.v:2.418-2.436" *)
  wire _136_;
  (* src = "./verilog/b10_C.v:2.362-2.380" *)
  wire _137_;
  (* src = "./verilog/b10_C.v:2.50-2.53" *)
  wire _138_;
  (* src = "./verilog/b10_C.v:2.45-2.48" *)
  wire _139_;
  (* src = "./verilog/b10_C.v:2.7-2.15" *)
  wire _140_;
  (* src = "./verilog/b10_C.v:2.286-2.305" *)
  wire _141_;
  (* src = "./verilog/b10_C.v:2.32-2.37" *)
  wire _142_;
  (* src = "./verilog/b10_C.v:2.176-2.196" *)
  wire _143_;
  (* src = "./verilog/b10_C.v:2.154-2.174" *)
  wire _144_;
  (* src = "./verilog/b10_C.v:2.132-2.152" *)
  wire _145_;
  (* src = "./verilog/b10_C.v:2.110-2.130" *)
  wire _146_;
  (* src = "./verilog/b10_C.v:2.39-2.43" *)
  wire _147_;
  (* src = "./verilog/b10_C.v:3.8-3.12" *)
  wire _148_;
  (* src = "./verilog/b10_C.v:3.14-3.18" *)
  wire _149_;
  (* src = "./verilog/b10_C.v:3.20-3.24" *)
  wire _150_;
  (* src = "./verilog/b10_C.v:3.26-3.30" *)
  wire _151_;
  (* src = "./verilog/b10_C.v:3.32-3.36" *)
  wire _152_;
  (* src = "./verilog/b10_C.v:3.38-3.42" *)
  wire _153_;
  (* src = "./verilog/b10_C.v:3.44-3.48" *)
  wire _154_;
  (* src = "./verilog/b10_C.v:3.50-3.54" *)
  wire _155_;
  (* src = "./verilog/b10_C.v:3.56-3.60" *)
  wire _156_;
  (* src = "./verilog/b10_C.v:3.62-3.66" *)
  wire _157_;
  (* src = "./verilog/b10_C.v:3.68-3.72" *)
  wire _158_;
  (* src = "./verilog/b10_C.v:3.74-3.78" *)
  wire _159_;
  (* src = "./verilog/b10_C.v:3.80-3.84" *)
  wire _160_;
  (* src = "./verilog/b10_C.v:3.86-3.90" *)
  wire _161_;
  (* src = "./verilog/b10_C.v:3.92-3.96" *)
  wire _162_;
  (* src = "./verilog/b10_C.v:3.98-3.102" *)
  wire _163_;
  (* src = "./verilog/b10_C.v:3.104-3.108" *)
  wire _164_;
  (* src = "./verilog/b10_C.v:2.55-2.72" *)
  wire _165_;
  (* src = "./verilog/b10_C.v:2.307-2.324" *)
  wire _166_;
  (* src = "./verilog/b10_C.v:2.399-2.416" *)
  wire _167_;
  (* src = "./verilog/b10_C.v:2.343-2.360" *)
  wire _168_;
  (* src = "./verilog/b10_C.v:2.101-2.108" *)
  wire _169_;
  (* src = "./verilog/b10_C.v:2.92-2.99" *)
  wire _170_;
  (* src = "./verilog/b10_C.v:2.83-2.90" *)
  wire _171_;
  (* src = "./verilog/b10_C.v:2.74-2.81" *)
  wire _172_;
  (* src = "./verilog/b10_C.v:2.264-2.284" *)
  wire _173_;
  (* src = "./verilog/b10_C.v:2.242-2.262" *)
  wire _174_;
  (* src = "./verilog/b10_C.v:2.220-2.240" *)
  wire _175_;
  (* src = "./verilog/b10_C.v:2.198-2.218" *)
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  (* src = "./verilog/b10_C.v:2.326-2.341" *)
  input CTR_REG_SCAN_IN;
  (* src = "./verilog/b10_C.v:2.382-2.397" *)
  input CTS_REG_SCAN_IN;
  (* src = "./verilog/b10_C.v:2.17-2.25" *)
  input G_BUTTON;
  (* src = "./verilog/b10_C.v:2.27-2.30" *)
  input KEY;
  (* src = "./verilog/b10_C.v:2.418-2.436" *)
  input LAST_G_REG_SCAN_IN;
  (* src = "./verilog/b10_C.v:2.362-2.380" *)
  input LAST_R_REG_SCAN_IN;
  (* src = "./verilog/b10_C.v:2.50-2.53" *)
  input RTR;
  (* src = "./verilog/b10_C.v:2.45-2.48" *)
  input RTS;
  (* src = "./verilog/b10_C.v:2.7-2.15" *)
  input R_BUTTON;
  (* src = "./verilog/b10_C.v:2.286-2.305" *)
  input SIGN_REG_3__SCAN_IN;
  (* src = "./verilog/b10_C.v:2.32-2.37" *)
  input START;
  (* src = "./verilog/b10_C.v:2.176-2.196" *)
  input STATO_REG_0__SCAN_IN;
  (* src = "./verilog/b10_C.v:2.154-2.174" *)
  input STATO_REG_1__SCAN_IN;
  (* src = "./verilog/b10_C.v:2.132-2.152" *)
  input STATO_REG_2__SCAN_IN;
  (* src = "./verilog/b10_C.v:2.110-2.130" *)
  input STATO_REG_3__SCAN_IN;
  (* src = "./verilog/b10_C.v:2.39-2.43" *)
  input TEST;
  (* src = "./verilog/b10_C.v:3.8-3.12" *)
  output U207;
  (* src = "./verilog/b10_C.v:3.14-3.18" *)
  output U208;
  (* src = "./verilog/b10_C.v:3.20-3.24" *)
  output U209;
  (* src = "./verilog/b10_C.v:3.26-3.30" *)
  output U210;
  (* src = "./verilog/b10_C.v:3.32-3.36" *)
  output U211;
  (* src = "./verilog/b10_C.v:3.38-3.42" *)
  output U212;
  (* src = "./verilog/b10_C.v:3.44-3.48" *)
  output U233;
  (* src = "./verilog/b10_C.v:3.50-3.54" *)
  output U234;
  (* src = "./verilog/b10_C.v:3.56-3.60" *)
  output U235;
  (* src = "./verilog/b10_C.v:3.62-3.66" *)
  output U236;
  (* src = "./verilog/b10_C.v:3.68-3.72" *)
  output U237;
  (* src = "./verilog/b10_C.v:3.74-3.78" *)
  output U238;
  (* src = "./verilog/b10_C.v:3.80-3.84" *)
  output U239;
  (* src = "./verilog/b10_C.v:3.86-3.90" *)
  output U240;
  (* src = "./verilog/b10_C.v:3.92-3.96" *)
  output U241;
  (* src = "./verilog/b10_C.v:3.98-3.102" *)
  output U242;
  (* src = "./verilog/b10_C.v:3.104-3.108" *)
  output U243;
  (* src = "./verilog/b10_C.v:2.55-2.72" *)
  input VOTO0_REG_SCAN_IN;
  (* src = "./verilog/b10_C.v:2.307-2.324" *)
  input VOTO1_REG_SCAN_IN;
  (* src = "./verilog/b10_C.v:2.399-2.416" *)
  input VOTO2_REG_SCAN_IN;
  (* src = "./verilog/b10_C.v:2.343-2.360" *)
  input VOTO3_REG_SCAN_IN;
  (* src = "./verilog/b10_C.v:2.101-2.108" *)
  input V_IN_0_;
  (* src = "./verilog/b10_C.v:2.92-2.99" *)
  input V_IN_1_;
  (* src = "./verilog/b10_C.v:2.83-2.90" *)
  input V_IN_2_;
  (* src = "./verilog/b10_C.v:2.74-2.81" *)
  input V_IN_3_;
  (* src = "./verilog/b10_C.v:2.264-2.284" *)
  input V_OUT_REG_0__SCAN_IN;
  (* src = "./verilog/b10_C.v:2.242-2.262" *)
  input V_OUT_REG_1__SCAN_IN;
  (* src = "./verilog/b10_C.v:2.220-2.240" *)
  input V_OUT_REG_2__SCAN_IN;
  (* src = "./verilog/b10_C.v:2.198-2.218" *)
  input V_OUT_REG_3__SCAN_IN;
  NOT _325_ (
    .A(_143_),
    .Y(_272_)
  );
  NOT _326_ (
    .A(_145_),
    .Y(_273_)
  );
  NOT _327_ (
    .A(_139_),
    .Y(_274_)
  );
  NOT _328_ (
    .A(_146_),
    .Y(_275_)
  );
  NOT _329_ (
    .A(_165_),
    .Y(_276_)
  );
  OR _330_ (
    .A(_143_),
    .B(_146_),
    .Y(_277_)
  );
  AND _331_ (
    .A(_169_),
    .B(_170_),
    .Y(_278_)
  );
  AND _332_ (
    .A(_171_),
    .B(_172_),
    .Y(_279_)
  );
  NAND _333_ (
    .A(_278_),
    .B(_279_),
    .Y(_280_)
  );
  NAND _334_ (
    .A(_143_),
    .B(_280_),
    .Y(_281_)
  );
  NOR _335_ (
    .A(_144_),
    .B(_143_),
    .Y(_282_)
  );
  AND _336_ (
    .A(_138_),
    .B(_282_),
    .Y(_283_)
  );
  AND _337_ (
    .A(_144_),
    .B(_145_),
    .Y(_284_)
  );
  NAND _338_ (
    .A(_272_),
    .B(_284_),
    .Y(_285_)
  );
  NOR _339_ (
    .A(_275_),
    .B(_283_),
    .Y(_286_)
  );
  AND _340_ (
    .A(_285_),
    .B(_286_),
    .Y(_287_)
  );
  NAND _341_ (
    .A(_281_),
    .B(_287_),
    .Y(_288_)
  );
  OR _342_ (
    .A(_274_),
    .B(_285_),
    .Y(_289_)
  );
  NOR _343_ (
    .A(_145_),
    .B(_146_),
    .Y(_290_)
  );
  AND _344_ (
    .A(_272_),
    .B(_290_),
    .Y(_291_)
  );
  NAND _345_ (
    .A(_272_),
    .B(_290_),
    .Y(_292_)
  );
  NAND _346_ (
    .A(_282_),
    .B(_290_),
    .Y(_293_)
  );
  AND _347_ (
    .A(_289_),
    .B(_293_),
    .Y(_294_)
  );
  AND _348_ (
    .A(_144_),
    .B(_143_),
    .Y(_295_)
  );
  NOR _349_ (
    .A(_273_),
    .B(_138_),
    .Y(_296_)
  );
  NAND _350_ (
    .A(_295_),
    .B(_296_),
    .Y(_297_)
  );
  AND _351_ (
    .A(_144_),
    .B(_273_),
    .Y(_298_)
  );
  NOR _352_ (
    .A(_146_),
    .B(_142_),
    .Y(_299_)
  );
  OR _353_ (
    .A(_146_),
    .B(_142_),
    .Y(_300_)
  );
  NAND _354_ (
    .A(_298_),
    .B(_299_),
    .Y(_301_)
  );
  OR _355_ (
    .A(_144_),
    .B(_272_),
    .Y(_302_)
  );
  NAND _356_ (
    .A(_145_),
    .B(_274_),
    .Y(_303_)
  );
  OR _357_ (
    .A(_302_),
    .B(_303_),
    .Y(_304_)
  );
  AND _358_ (
    .A(_145_),
    .B(_282_),
    .Y(_305_)
  );
  AND _359_ (
    .A(_145_),
    .B(_283_),
    .Y(_306_)
  );
  NAND _360_ (
    .A(_145_),
    .B(_283_),
    .Y(_307_)
  );
  NAND _361_ (
    .A(_142_),
    .B(_290_),
    .Y(_308_)
  );
  OR _362_ (
    .A(_272_),
    .B(_308_),
    .Y(_309_)
  );
  AND _363_ (
    .A(_297_),
    .B(_301_),
    .Y(_310_)
  );
  AND _364_ (
    .A(_307_),
    .B(_310_),
    .Y(_311_)
  );
  AND _365_ (
    .A(_304_),
    .B(_309_),
    .Y(_312_)
  );
  AND _366_ (
    .A(_294_),
    .B(_312_),
    .Y(_313_)
  );
  AND _367_ (
    .A(_288_),
    .B(_313_),
    .Y(_314_)
  );
  NAND _368_ (
    .A(_311_),
    .B(_314_),
    .Y(_315_)
  );
  NAND _369_ (
    .A(_277_),
    .B(_315_),
    .Y(_316_)
  );
  NAND _370_ (
    .A(_144_),
    .B(_316_),
    .Y(_317_)
  );
  NAND _371_ (
    .A(_143_),
    .B(_146_),
    .Y(_318_)
  );
  NAND _372_ (
    .A(_302_),
    .B(_318_),
    .Y(_319_)
  );
  NAND _373_ (
    .A(_315_),
    .B(_319_),
    .Y(_320_)
  );
  AND _374_ (
    .A(_285_),
    .B(_320_),
    .Y(_321_)
  );
  NAND _375_ (
    .A(_317_),
    .B(_321_),
    .Y(_151_)
  );
  AND _376_ (
    .A(_276_),
    .B(_167_),
    .Y(_322_)
  );
  NAND _377_ (
    .A(_166_),
    .B(_322_),
    .Y(_323_)
  );
  NOR _378_ (
    .A(_168_),
    .B(_323_),
    .Y(_324_)
  );
  OR _379_ (
    .A(_143_),
    .B(_324_),
    .Y(_177_)
  );
  AND _380_ (
    .A(_302_),
    .B(_177_),
    .Y(_178_)
  );
  NAND _381_ (
    .A(_315_),
    .B(_178_),
    .Y(_179_)
  );
  NAND _382_ (
    .A(_145_),
    .B(_179_),
    .Y(_180_)
  );
  AND _383_ (
    .A(_144_),
    .B(_318_),
    .Y(_181_)
  );
  NAND _384_ (
    .A(_292_),
    .B(_181_),
    .Y(_182_)
  );
  NAND _385_ (
    .A(_180_),
    .B(_182_),
    .Y(_152_)
  );
  AND _386_ (
    .A(_273_),
    .B(_318_),
    .Y(_183_)
  );
  NOR _387_ (
    .A(_295_),
    .B(_183_),
    .Y(_184_)
  );
  AND _388_ (
    .A(_138_),
    .B(_277_),
    .Y(_185_)
  );
  OR _389_ (
    .A(_298_),
    .B(_185_),
    .Y(_186_)
  );
  OR _390_ (
    .A(_184_),
    .B(_186_),
    .Y(_187_)
  );
  NAND _391_ (
    .A(_133_),
    .B(_187_),
    .Y(_188_)
  );
  OR _392_ (
    .A(_138_),
    .B(_146_),
    .Y(_189_)
  );
  NOR _393_ (
    .A(_145_),
    .B(_302_),
    .Y(_190_)
  );
  AND _394_ (
    .A(_275_),
    .B(_190_),
    .Y(_191_)
  );
  OR _395_ (
    .A(_305_),
    .B(_191_),
    .Y(_192_)
  );
  NAND _396_ (
    .A(_189_),
    .B(_192_),
    .Y(_193_)
  );
  NAND _397_ (
    .A(_188_),
    .B(_193_),
    .Y(_148_)
  );
  AND _398_ (
    .A(_144_),
    .B(_135_),
    .Y(_194_)
  );
  NAND _399_ (
    .A(_291_),
    .B(_194_),
    .Y(_195_)
  );
  AND _400_ (
    .A(_142_),
    .B(_291_),
    .Y(_196_)
  );
  AND _401_ (
    .A(_194_),
    .B(_196_),
    .Y(_197_)
  );
  NAND _402_ (
    .A(_194_),
    .B(_196_),
    .Y(_198_)
  );
  NAND _403_ (
    .A(_134_),
    .B(_197_),
    .Y(_199_)
  );
  NAND _404_ (
    .A(_136_),
    .B(_198_),
    .Y(_200_)
  );
  NAND _405_ (
    .A(_199_),
    .B(_200_),
    .Y(_163_)
  );
  NAND _406_ (
    .A(_140_),
    .B(_197_),
    .Y(_201_)
  );
  NAND _407_ (
    .A(_137_),
    .B(_198_),
    .Y(_202_)
  );
  NAND _408_ (
    .A(_201_),
    .B(_202_),
    .Y(_161_)
  );
  NAND _409_ (
    .A(_165_),
    .B(_306_),
    .Y(_203_)
  );
  NAND _410_ (
    .A(_173_),
    .B(_307_),
    .Y(_204_)
  );
  NAND _411_ (
    .A(_203_),
    .B(_204_),
    .Y(_158_)
  );
  NAND _412_ (
    .A(_166_),
    .B(_306_),
    .Y(_205_)
  );
  NAND _413_ (
    .A(_174_),
    .B(_307_),
    .Y(_206_)
  );
  NAND _414_ (
    .A(_205_),
    .B(_206_),
    .Y(_157_)
  );
  NAND _415_ (
    .A(_167_),
    .B(_306_),
    .Y(_207_)
  );
  NAND _416_ (
    .A(_175_),
    .B(_307_),
    .Y(_208_)
  );
  NAND _417_ (
    .A(_207_),
    .B(_208_),
    .Y(_156_)
  );
  NAND _418_ (
    .A(_168_),
    .B(_306_),
    .Y(_209_)
  );
  NAND _419_ (
    .A(_176_),
    .B(_307_),
    .Y(_210_)
  );
  NAND _420_ (
    .A(_209_),
    .B(_210_),
    .Y(_155_)
  );
  OR _421_ (
    .A(_147_),
    .B(_293_),
    .Y(_211_)
  );
  NAND _422_ (
    .A(_141_),
    .B(_211_),
    .Y(_212_)
  );
  NAND _423_ (
    .A(_318_),
    .B(_212_),
    .Y(_150_)
  );
  NAND _424_ (
    .A(_132_),
    .B(_294_),
    .Y(_213_)
  );
  NAND _425_ (
    .A(_304_),
    .B(_213_),
    .Y(_149_)
  );
  NAND _426_ (
    .A(_300_),
    .B(_190_),
    .Y(_214_)
  );
  AND _427_ (
    .A(_294_),
    .B(_214_),
    .Y(_215_)
  );
  OR _428_ (
    .A(_135_),
    .B(_308_),
    .Y(_216_)
  );
  OR _429_ (
    .A(_143_),
    .B(_216_),
    .Y(_217_)
  );
  AND _430_ (
    .A(_215_),
    .B(_217_),
    .Y(_218_)
  );
  NAND _431_ (
    .A(_134_),
    .B(_196_),
    .Y(_219_)
  );
  OR _432_ (
    .A(_136_),
    .B(_219_),
    .Y(_220_)
  );
  NAND _433_ (
    .A(_218_),
    .B(_220_),
    .Y(_221_)
  );
  OR _434_ (
    .A(_166_),
    .B(_221_),
    .Y(_222_)
  );
  NAND _435_ (
    .A(_135_),
    .B(_298_),
    .Y(_223_)
  );
  OR _436_ (
    .A(_166_),
    .B(_223_),
    .Y(_224_)
  );
  NAND _437_ (
    .A(_146_),
    .B(_190_),
    .Y(_225_)
  );
  OR _438_ (
    .A(_146_),
    .B(_285_),
    .Y(_226_)
  );
  NAND _439_ (
    .A(_225_),
    .B(_226_),
    .Y(_227_)
  );
  NAND _440_ (
    .A(_170_),
    .B(_227_),
    .Y(_228_)
  );
  AND _441_ (
    .A(_224_),
    .B(_228_),
    .Y(_229_)
  );
  NAND _442_ (
    .A(_221_),
    .B(_229_),
    .Y(_230_)
  );
  AND _443_ (
    .A(_222_),
    .B(_230_),
    .Y(_159_)
  );
  AND _444_ (
    .A(_308_),
    .B(_225_),
    .Y(_231_)
  );
  AND _445_ (
    .A(_277_),
    .B(_298_),
    .Y(_232_)
  );
  NAND _446_ (
    .A(_318_),
    .B(_232_),
    .Y(_233_)
  );
  AND _447_ (
    .A(_294_),
    .B(_233_),
    .Y(_234_)
  );
  NAND _448_ (
    .A(_231_),
    .B(_234_),
    .Y(_235_)
  );
  OR _449_ (
    .A(_165_),
    .B(_235_),
    .Y(_236_)
  );
  NAND _450_ (
    .A(_169_),
    .B(_227_),
    .Y(_237_)
  );
  NAND _451_ (
    .A(_144_),
    .B(_146_),
    .Y(_238_)
  );
  OR _452_ (
    .A(_141_),
    .B(_238_),
    .Y(_239_)
  );
  AND _453_ (
    .A(_195_),
    .B(_239_),
    .Y(_240_)
  );
  AND _454_ (
    .A(_237_),
    .B(_240_),
    .Y(_241_)
  );
  NAND _455_ (
    .A(_235_),
    .B(_241_),
    .Y(_242_)
  );
  AND _456_ (
    .A(_236_),
    .B(_242_),
    .Y(_164_)
  );
  NAND _457_ (
    .A(_290_),
    .B(_295_),
    .Y(_243_)
  );
  AND _458_ (
    .A(_215_),
    .B(_243_),
    .Y(_244_)
  );
  NAND _459_ (
    .A(_216_),
    .B(_244_),
    .Y(_245_)
  );
  OR _460_ (
    .A(_168_),
    .B(_245_),
    .Y(_246_)
  );
  XOR _461_ (
    .A(_165_),
    .B(_167_),
    .Y(_247_)
  );
  XOR _462_ (
    .A(_166_),
    .B(_247_),
    .Y(_248_)
  );
  NAND _463_ (
    .A(_295_),
    .B(_248_),
    .Y(_249_)
  );
  NAND _464_ (
    .A(_172_),
    .B(_227_),
    .Y(_250_)
  );
  AND _465_ (
    .A(_249_),
    .B(_250_),
    .Y(_251_)
  );
  NAND _466_ (
    .A(_245_),
    .B(_251_),
    .Y(_252_)
  );
  AND _467_ (
    .A(_246_),
    .B(_252_),
    .Y(_160_)
  );
  NAND _468_ (
    .A(_140_),
    .B(_196_),
    .Y(_253_)
  );
  OR _469_ (
    .A(_137_),
    .B(_253_),
    .Y(_254_)
  );
  NAND _470_ (
    .A(_218_),
    .B(_254_),
    .Y(_255_)
  );
  OR _471_ (
    .A(_167_),
    .B(_255_),
    .Y(_256_)
  );
  OR _472_ (
    .A(_167_),
    .B(_223_),
    .Y(_257_)
  );
  NAND _473_ (
    .A(_171_),
    .B(_227_),
    .Y(_258_)
  );
  AND _474_ (
    .A(_257_),
    .B(_258_),
    .Y(_259_)
  );
  NAND _475_ (
    .A(_255_),
    .B(_259_),
    .Y(_260_)
  );
  AND _476_ (
    .A(_256_),
    .B(_260_),
    .Y(_162_)
  );
  NAND _477_ (
    .A(_305_),
    .B(_324_),
    .Y(_261_)
  );
  AND _478_ (
    .A(_211_),
    .B(_261_),
    .Y(_262_)
  );
  NAND _479_ (
    .A(_315_),
    .B(_262_),
    .Y(_263_)
  );
  OR _480_ (
    .A(_146_),
    .B(_315_),
    .Y(_264_)
  );
  NAND _481_ (
    .A(_263_),
    .B(_264_),
    .Y(_265_)
  );
  NAND _482_ (
    .A(_318_),
    .B(_265_),
    .Y(_153_)
  );
  NAND _483_ (
    .A(_275_),
    .B(_324_),
    .Y(_266_)
  );
  NAND _484_ (
    .A(_282_),
    .B(_266_),
    .Y(_267_)
  );
  AND _485_ (
    .A(_285_),
    .B(_292_),
    .Y(_268_)
  );
  AND _486_ (
    .A(_267_),
    .B(_268_),
    .Y(_269_)
  );
  OR _487_ (
    .A(_143_),
    .B(_315_),
    .Y(_270_)
  );
  NAND _488_ (
    .A(_315_),
    .B(_269_),
    .Y(_271_)
  );
  AND _489_ (
    .A(_270_),
    .B(_271_),
    .Y(_154_)
  );
  assign _144_ = STATO_REG_1__SCAN_IN;
  assign _143_ = STATO_REG_0__SCAN_IN;
  assign _145_ = STATO_REG_2__SCAN_IN;
  assign _138_ = RTR;
  assign _139_ = RTS;
  assign _171_ = V_IN_2_;
  assign _172_ = V_IN_3_;
  assign _169_ = V_IN_0_;
  assign _170_ = V_IN_1_;
  assign _146_ = STATO_REG_3__SCAN_IN;
  assign _142_ = START;
  assign U210 = _151_;
  assign _165_ = VOTO0_REG_SCAN_IN;
  assign _168_ = VOTO3_REG_SCAN_IN;
  assign _166_ = VOTO1_REG_SCAN_IN;
  assign _167_ = VOTO2_REG_SCAN_IN;
  assign U211 = _152_;
  assign _133_ = CTS_REG_SCAN_IN;
  assign U207 = _148_;
  assign _135_ = KEY;
  assign _134_ = G_BUTTON;
  assign _136_ = LAST_G_REG_SCAN_IN;
  assign U242 = _163_;
  assign _140_ = R_BUTTON;
  assign _137_ = LAST_R_REG_SCAN_IN;
  assign U240 = _161_;
  assign _173_ = V_OUT_REG_0__SCAN_IN;
  assign U237 = _158_;
  assign _174_ = V_OUT_REG_1__SCAN_IN;
  assign U236 = _157_;
  assign _175_ = V_OUT_REG_2__SCAN_IN;
  assign U235 = _156_;
  assign _176_ = V_OUT_REG_3__SCAN_IN;
  assign U234 = _155_;
  assign _147_ = TEST;
  assign _141_ = SIGN_REG_3__SCAN_IN;
  assign U209 = _150_;
  assign _132_ = CTR_REG_SCAN_IN;
  assign U208 = _149_;
  assign U238 = _159_;
  assign U243 = _164_;
  assign U239 = _160_;
  assign U241 = _162_;
  assign U212 = _153_;
  assign U233 = _154_;
endmodule
