/* Generated by Yosys 0.10+12 (git sha1 UNKNOWN, gcc 10.1.0 -fPIC -Os) */

(* top =  1  *)
(* src = "./verilog/b13_C.v:1.1-294.10" *)
module b13_C(EOC, DATA_IN_7_, DATA_IN_6_, DATA_IN_5_, DATA_IN_4_, DATA_IN_3_, DATA_IN_2_, DATA_IN_1_, DATA_IN_0_, DSR, TX_END_REG_SCAN_IN, S2_REG_0__SCAN_IN, S2_REG_1__SCAN_IN, CANALE_REG_3__SCAN_IN, CANALE_REG_2__SCAN_IN, CANALE_REG_1__SCAN_IN, CANALE_REG_0__SCAN_IN, CONTA_TMP_REG_3__SCAN_IN, CONTA_TMP_REG_2__SCAN_IN, CONTA_TMP_REG_1__SCAN_IN, CONTA_TMP_REG_0__SCAN_IN, ITFC_STATE_REG_1__SCAN_IN, ITFC_STATE_REG_0__SCAN_IN, OUT_REG_REG_7__SCAN_IN, OUT_REG_REG_6__SCAN_IN, OUT_REG_REG_5__SCAN_IN, OUT_REG_REG_4__SCAN_IN, OUT_REG_REG_3__SCAN_IN, OUT_REG_REG_2__SCAN_IN, OUT_REG_REG_1__SCAN_IN, OUT_REG_REG_0__SCAN_IN, NEXT_BIT_REG_3__SCAN_IN, NEXT_BIT_REG_2__SCAN_IN, NEXT_BIT_REG_1__SCAN_IN, NEXT_BIT_REG_0__SCAN_IN, TX_CONTA_REG_9__SCAN_IN, TX_CONTA_REG_8__SCAN_IN, TX_CONTA_REG_7__SCAN_IN, TX_CONTA_REG_6__SCAN_IN, TX_CONTA_REG_5__SCAN_IN, TX_CONTA_REG_4__SCAN_IN, TX_CONTA_REG_3__SCAN_IN, TX_CONTA_REG_2__SCAN_IN, TX_CONTA_REG_1__SCAN_IN, TX_CONTA_REG_0__SCAN_IN, LOAD_REG_SCAN_IN, SEND_DATA_REG_SCAN_IN, SEND_EN_REG_SCAN_IN, MUX_EN_REG_SCAN_IN, TRE_REG_SCAN_IN, LOAD_DATO_REG_SCAN_IN, SOC_REG_SCAN_IN, SEND_REG_SCAN_IN, MPX_REG_SCAN_IN, CONFIRM_REG_SCAN_IN, SHOT_REG_SCAN_IN, ADD_MPX2_REG_SCAN_IN, RDY_REG_SCAN_IN, ERROR_REG_SCAN_IN, S1_REG_2__SCAN_IN, S1_REG_1__SCAN_IN, S1_REG_0__SCAN_IN, U380, U381, U382, U383, U384, U385, U386, U387, U388, U389, U390, U391, U392, U393, U394, U395, U396, U397, U398, U399, U400, U401, U402, U403, U404, U405, U406, U407, U408, U409, U410, U411, U412, U413, U414, U415, U416, U417, U450, U451, U452, U453, U454, U455, U456, U457, U458, U459, U460, U461, U462, U463, U464);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  (* src = "./verilog/b13_C.v:2.1176-2.1196" *)
  wire _154_;
  (* src = "./verilog/b13_C.v:2.240-2.261" *)
  wire _155_;
  (* src = "./verilog/b13_C.v:2.217-2.238" *)
  wire _156_;
  (* src = "./verilog/b13_C.v:2.194-2.215" *)
  wire _157_;
  (* src = "./verilog/b13_C.v:2.171-2.192" *)
  wire _158_;
  (* src = "./verilog/b13_C.v:2.1137-2.1156" *)
  wire _159_;
  (* src = "./verilog/b13_C.v:2.341-2.365" *)
  wire _160_;
  (* src = "./verilog/b13_C.v:2.315-2.339" *)
  wire _161_;
  (* src = "./verilog/b13_C.v:2.289-2.313" *)
  wire _162_;
  (* src = "./verilog/b13_C.v:2.263-2.287" *)
  wire _163_;
  (* src = "./verilog/b13_C.v:2.96-2.106" *)
  wire _164_;
  (* src = "./verilog/b13_C.v:2.84-2.94" *)
  wire _165_;
  (* src = "./verilog/b13_C.v:2.72-2.82" *)
  wire _166_;
  (* src = "./verilog/b13_C.v:2.60-2.70" *)
  wire _167_;
  (* src = "./verilog/b13_C.v:2.48-2.58" *)
  wire _168_;
  (* src = "./verilog/b13_C.v:2.36-2.46" *)
  wire _169_;
  (* src = "./verilog/b13_C.v:2.24-2.34" *)
  wire _170_;
  (* src = "./verilog/b13_C.v:2.12-2.22" *)
  wire _171_;
  (* src = "./verilog/b13_C.v:2.108-2.111" *)
  wire _172_;
  (* src = "./verilog/b13_C.v:2.7-2.10" *)
  wire _173_;
  (* src = "./verilog/b13_C.v:2.1215-2.1232" *)
  wire _174_;
  (* src = "./verilog/b13_C.v:2.394-2.419" *)
  wire _175_;
  (* src = "./verilog/b13_C.v:2.367-2.392" *)
  wire _176_;
  (* src = "./verilog/b13_C.v:2.1062-2.1083" *)
  wire _177_;
  (* src = "./verilog/b13_C.v:2.963-2.979" *)
  wire _178_;
  (* src = "./verilog/b13_C.v:2.1120-2.1135" *)
  wire _179_;
  (* src = "./verilog/b13_C.v:2.1025-2.1043" *)
  wire _180_;
  (* src = "./verilog/b13_C.v:2.688-2.711" *)
  wire _181_;
  (* src = "./verilog/b13_C.v:2.663-2.686" *)
  wire _182_;
  (* src = "./verilog/b13_C.v:2.638-2.661" *)
  wire _183_;
  (* src = "./verilog/b13_C.v:2.613-2.636" *)
  wire _184_;
  (* src = "./verilog/b13_C.v:2.589-2.611" *)
  wire _185_;
  (* src = "./verilog/b13_C.v:2.565-2.587" *)
  wire _186_;
  (* src = "./verilog/b13_C.v:2.541-2.563" *)
  wire _187_;
  (* src = "./verilog/b13_C.v:2.517-2.539" *)
  wire _188_;
  (* src = "./verilog/b13_C.v:2.493-2.515" *)
  wire _189_;
  (* src = "./verilog/b13_C.v:2.469-2.491" *)
  wire _190_;
  (* src = "./verilog/b13_C.v:2.445-2.467" *)
  wire _191_;
  (* src = "./verilog/b13_C.v:2.421-2.443" *)
  wire _192_;
  (* src = "./verilog/b13_C.v:2.1198-2.1213" *)
  wire _193_;
  (* src = "./verilog/b13_C.v:2.1272-2.1289" *)
  wire _194_;
  (* src = "./verilog/b13_C.v:2.1253-2.1270" *)
  wire _195_;
  (* src = "./verilog/b13_C.v:2.1234-2.1251" *)
  wire _196_;
  (* src = "./verilog/b13_C.v:2.133-2.150" *)
  wire _197_;
  (* src = "./verilog/b13_C.v:2.152-2.169" *)
  wire _198_;
  (* src = "./verilog/b13_C.v:2.981-2.1002" *)
  wire _199_;
  (* src = "./verilog/b13_C.v:2.1004-2.1023" *)
  wire _200_;
  (* src = "./verilog/b13_C.v:2.1102-2.1118" *)
  wire _201_;
  (* src = "./verilog/b13_C.v:2.1158-2.1174" *)
  wire _202_;
  (* src = "./verilog/b13_C.v:2.1085-2.1100" *)
  wire _203_;
  (* src = "./verilog/b13_C.v:2.1045-2.1060" *)
  wire _204_;
  (* src = "./verilog/b13_C.v:2.938-2.961" *)
  wire _205_;
  (* src = "./verilog/b13_C.v:2.913-2.936" *)
  wire _206_;
  (* src = "./verilog/b13_C.v:2.888-2.911" *)
  wire _207_;
  (* src = "./verilog/b13_C.v:2.863-2.886" *)
  wire _208_;
  (* src = "./verilog/b13_C.v:2.838-2.861" *)
  wire _209_;
  (* src = "./verilog/b13_C.v:2.813-2.836" *)
  wire _210_;
  (* src = "./verilog/b13_C.v:2.788-2.811" *)
  wire _211_;
  (* src = "./verilog/b13_C.v:2.763-2.786" *)
  wire _212_;
  (* src = "./verilog/b13_C.v:2.738-2.761" *)
  wire _213_;
  (* src = "./verilog/b13_C.v:2.713-2.736" *)
  wire _214_;
  (* src = "./verilog/b13_C.v:2.113-2.131" *)
  wire _215_;
  (* src = "./verilog/b13_C.v:3.8-3.12" *)
  wire _216_;
  (* src = "./verilog/b13_C.v:3.14-3.18" *)
  wire _217_;
  (* src = "./verilog/b13_C.v:3.20-3.24" *)
  wire _218_;
  (* src = "./verilog/b13_C.v:3.26-3.30" *)
  wire _219_;
  (* src = "./verilog/b13_C.v:3.32-3.36" *)
  wire _220_;
  (* src = "./verilog/b13_C.v:3.38-3.42" *)
  wire _221_;
  (* src = "./verilog/b13_C.v:3.44-3.48" *)
  wire _222_;
  (* src = "./verilog/b13_C.v:3.50-3.54" *)
  wire _223_;
  (* src = "./verilog/b13_C.v:3.56-3.60" *)
  wire _224_;
  (* src = "./verilog/b13_C.v:3.62-3.66" *)
  wire _225_;
  (* src = "./verilog/b13_C.v:3.68-3.72" *)
  wire _226_;
  (* src = "./verilog/b13_C.v:3.74-3.78" *)
  wire _227_;
  (* src = "./verilog/b13_C.v:3.80-3.84" *)
  wire _228_;
  (* src = "./verilog/b13_C.v:3.86-3.90" *)
  wire _229_;
  (* src = "./verilog/b13_C.v:3.92-3.96" *)
  wire _230_;
  (* src = "./verilog/b13_C.v:3.98-3.102" *)
  wire _231_;
  (* src = "./verilog/b13_C.v:3.104-3.108" *)
  wire _232_;
  (* src = "./verilog/b13_C.v:3.110-3.114" *)
  wire _233_;
  (* src = "./verilog/b13_C.v:3.116-3.120" *)
  wire _234_;
  (* src = "./verilog/b13_C.v:3.122-3.126" *)
  wire _235_;
  (* src = "./verilog/b13_C.v:3.128-3.132" *)
  wire _236_;
  (* src = "./verilog/b13_C.v:3.134-3.138" *)
  wire _237_;
  (* src = "./verilog/b13_C.v:3.140-3.144" *)
  wire _238_;
  (* src = "./verilog/b13_C.v:3.146-3.150" *)
  wire _239_;
  (* src = "./verilog/b13_C.v:3.152-3.156" *)
  wire _240_;
  (* src = "./verilog/b13_C.v:3.158-3.162" *)
  wire _241_;
  (* src = "./verilog/b13_C.v:3.164-3.168" *)
  wire _242_;
  (* src = "./verilog/b13_C.v:3.170-3.174" *)
  wire _243_;
  (* src = "./verilog/b13_C.v:3.176-3.180" *)
  wire _244_;
  (* src = "./verilog/b13_C.v:3.182-3.186" *)
  wire _245_;
  (* src = "./verilog/b13_C.v:3.188-3.192" *)
  wire _246_;
  (* src = "./verilog/b13_C.v:3.194-3.198" *)
  wire _247_;
  (* src = "./verilog/b13_C.v:3.200-3.204" *)
  wire _248_;
  (* src = "./verilog/b13_C.v:3.206-3.210" *)
  wire _249_;
  (* src = "./verilog/b13_C.v:3.212-3.216" *)
  wire _250_;
  (* src = "./verilog/b13_C.v:3.218-3.222" *)
  wire _251_;
  (* src = "./verilog/b13_C.v:3.224-3.228" *)
  wire _252_;
  (* src = "./verilog/b13_C.v:3.230-3.234" *)
  wire _253_;
  (* src = "./verilog/b13_C.v:3.236-3.240" *)
  wire _254_;
  (* src = "./verilog/b13_C.v:3.242-3.246" *)
  wire _255_;
  (* src = "./verilog/b13_C.v:3.248-3.252" *)
  wire _256_;
  (* src = "./verilog/b13_C.v:3.254-3.258" *)
  wire _257_;
  (* src = "./verilog/b13_C.v:3.260-3.264" *)
  wire _258_;
  (* src = "./verilog/b13_C.v:3.266-3.270" *)
  wire _259_;
  (* src = "./verilog/b13_C.v:3.272-3.276" *)
  wire _260_;
  (* src = "./verilog/b13_C.v:3.278-3.282" *)
  wire _261_;
  (* src = "./verilog/b13_C.v:3.284-3.288" *)
  wire _262_;
  (* src = "./verilog/b13_C.v:3.290-3.294" *)
  wire _263_;
  (* src = "./verilog/b13_C.v:3.296-3.300" *)
  wire _264_;
  (* src = "./verilog/b13_C.v:3.302-3.306" *)
  wire _265_;
  (* src = "./verilog/b13_C.v:3.308-3.312" *)
  wire _266_;
  (* src = "./verilog/b13_C.v:3.314-3.318" *)
  wire _267_;
  (* src = "./verilog/b13_C.v:3.320-3.324" *)
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  wire _432_;
  (* src = "./verilog/b13_C.v:2.1176-2.1196" *)
  input ADD_MPX2_REG_SCAN_IN;
  (* src = "./verilog/b13_C.v:2.240-2.261" *)
  input CANALE_REG_0__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.217-2.238" *)
  input CANALE_REG_1__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.194-2.215" *)
  input CANALE_REG_2__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.171-2.192" *)
  input CANALE_REG_3__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.1137-2.1156" *)
  input CONFIRM_REG_SCAN_IN;
  (* src = "./verilog/b13_C.v:2.341-2.365" *)
  input CONTA_TMP_REG_0__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.315-2.339" *)
  input CONTA_TMP_REG_1__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.289-2.313" *)
  input CONTA_TMP_REG_2__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.263-2.287" *)
  input CONTA_TMP_REG_3__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.96-2.106" *)
  input DATA_IN_0_;
  (* src = "./verilog/b13_C.v:2.84-2.94" *)
  input DATA_IN_1_;
  (* src = "./verilog/b13_C.v:2.72-2.82" *)
  input DATA_IN_2_;
  (* src = "./verilog/b13_C.v:2.60-2.70" *)
  input DATA_IN_3_;
  (* src = "./verilog/b13_C.v:2.48-2.58" *)
  input DATA_IN_4_;
  (* src = "./verilog/b13_C.v:2.36-2.46" *)
  input DATA_IN_5_;
  (* src = "./verilog/b13_C.v:2.24-2.34" *)
  input DATA_IN_6_;
  (* src = "./verilog/b13_C.v:2.12-2.22" *)
  input DATA_IN_7_;
  (* src = "./verilog/b13_C.v:2.108-2.111" *)
  input DSR;
  (* src = "./verilog/b13_C.v:2.7-2.10" *)
  input EOC;
  (* src = "./verilog/b13_C.v:2.1215-2.1232" *)
  input ERROR_REG_SCAN_IN;
  (* src = "./verilog/b13_C.v:2.394-2.419" *)
  input ITFC_STATE_REG_0__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.367-2.392" *)
  input ITFC_STATE_REG_1__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.1062-2.1083" *)
  input LOAD_DATO_REG_SCAN_IN;
  (* src = "./verilog/b13_C.v:2.963-2.979" *)
  input LOAD_REG_SCAN_IN;
  (* src = "./verilog/b13_C.v:2.1120-2.1135" *)
  input MPX_REG_SCAN_IN;
  (* src = "./verilog/b13_C.v:2.1025-2.1043" *)
  input MUX_EN_REG_SCAN_IN;
  (* src = "./verilog/b13_C.v:2.688-2.711" *)
  input NEXT_BIT_REG_0__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.663-2.686" *)
  input NEXT_BIT_REG_1__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.638-2.661" *)
  input NEXT_BIT_REG_2__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.613-2.636" *)
  input NEXT_BIT_REG_3__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.589-2.611" *)
  input OUT_REG_REG_0__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.565-2.587" *)
  input OUT_REG_REG_1__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.541-2.563" *)
  input OUT_REG_REG_2__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.517-2.539" *)
  input OUT_REG_REG_3__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.493-2.515" *)
  input OUT_REG_REG_4__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.469-2.491" *)
  input OUT_REG_REG_5__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.445-2.467" *)
  input OUT_REG_REG_6__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.421-2.443" *)
  input OUT_REG_REG_7__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.1198-2.1213" *)
  input RDY_REG_SCAN_IN;
  (* src = "./verilog/b13_C.v:2.1272-2.1289" *)
  input S1_REG_0__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.1253-2.1270" *)
  input S1_REG_1__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.1234-2.1251" *)
  input S1_REG_2__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.133-2.150" *)
  input S2_REG_0__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.152-2.169" *)
  input S2_REG_1__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.981-2.1002" *)
  input SEND_DATA_REG_SCAN_IN;
  (* src = "./verilog/b13_C.v:2.1004-2.1023" *)
  input SEND_EN_REG_SCAN_IN;
  (* src = "./verilog/b13_C.v:2.1102-2.1118" *)
  input SEND_REG_SCAN_IN;
  (* src = "./verilog/b13_C.v:2.1158-2.1174" *)
  input SHOT_REG_SCAN_IN;
  (* src = "./verilog/b13_C.v:2.1085-2.1100" *)
  input SOC_REG_SCAN_IN;
  (* src = "./verilog/b13_C.v:2.1045-2.1060" *)
  input TRE_REG_SCAN_IN;
  (* src = "./verilog/b13_C.v:2.938-2.961" *)
  input TX_CONTA_REG_0__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.913-2.936" *)
  input TX_CONTA_REG_1__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.888-2.911" *)
  input TX_CONTA_REG_2__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.863-2.886" *)
  input TX_CONTA_REG_3__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.838-2.861" *)
  input TX_CONTA_REG_4__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.813-2.836" *)
  input TX_CONTA_REG_5__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.788-2.811" *)
  input TX_CONTA_REG_6__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.763-2.786" *)
  input TX_CONTA_REG_7__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.738-2.761" *)
  input TX_CONTA_REG_8__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.713-2.736" *)
  input TX_CONTA_REG_9__SCAN_IN;
  (* src = "./verilog/b13_C.v:2.113-2.131" *)
  input TX_END_REG_SCAN_IN;
  (* src = "./verilog/b13_C.v:3.8-3.12" *)
  output U380;
  (* src = "./verilog/b13_C.v:3.14-3.18" *)
  output U381;
  (* src = "./verilog/b13_C.v:3.20-3.24" *)
  output U382;
  (* src = "./verilog/b13_C.v:3.26-3.30" *)
  output U383;
  (* src = "./verilog/b13_C.v:3.32-3.36" *)
  output U384;
  (* src = "./verilog/b13_C.v:3.38-3.42" *)
  output U385;
  (* src = "./verilog/b13_C.v:3.44-3.48" *)
  output U386;
  (* src = "./verilog/b13_C.v:3.50-3.54" *)
  output U387;
  (* src = "./verilog/b13_C.v:3.56-3.60" *)
  output U388;
  (* src = "./verilog/b13_C.v:3.62-3.66" *)
  output U389;
  (* src = "./verilog/b13_C.v:3.68-3.72" *)
  output U390;
  (* src = "./verilog/b13_C.v:3.74-3.78" *)
  output U391;
  (* src = "./verilog/b13_C.v:3.80-3.84" *)
  output U392;
  (* src = "./verilog/b13_C.v:3.86-3.90" *)
  output U393;
  (* src = "./verilog/b13_C.v:3.92-3.96" *)
  output U394;
  (* src = "./verilog/b13_C.v:3.98-3.102" *)
  output U395;
  (* src = "./verilog/b13_C.v:3.104-3.108" *)
  output U396;
  (* src = "./verilog/b13_C.v:3.110-3.114" *)
  output U397;
  (* src = "./verilog/b13_C.v:3.116-3.120" *)
  output U398;
  (* src = "./verilog/b13_C.v:3.122-3.126" *)
  output U399;
  (* src = "./verilog/b13_C.v:3.128-3.132" *)
  output U400;
  (* src = "./verilog/b13_C.v:3.134-3.138" *)
  output U401;
  (* src = "./verilog/b13_C.v:3.140-3.144" *)
  output U402;
  (* src = "./verilog/b13_C.v:3.146-3.150" *)
  output U403;
  (* src = "./verilog/b13_C.v:3.152-3.156" *)
  output U404;
  (* src = "./verilog/b13_C.v:3.158-3.162" *)
  output U405;
  (* src = "./verilog/b13_C.v:3.164-3.168" *)
  output U406;
  (* src = "./verilog/b13_C.v:3.170-3.174" *)
  output U407;
  (* src = "./verilog/b13_C.v:3.176-3.180" *)
  output U408;
  (* src = "./verilog/b13_C.v:3.182-3.186" *)
  output U409;
  (* src = "./verilog/b13_C.v:3.188-3.192" *)
  output U410;
  (* src = "./verilog/b13_C.v:3.194-3.198" *)
  output U411;
  (* src = "./verilog/b13_C.v:3.200-3.204" *)
  output U412;
  (* src = "./verilog/b13_C.v:3.206-3.210" *)
  output U413;
  (* src = "./verilog/b13_C.v:3.212-3.216" *)
  output U414;
  (* src = "./verilog/b13_C.v:3.218-3.222" *)
  output U415;
  (* src = "./verilog/b13_C.v:3.224-3.228" *)
  output U416;
  (* src = "./verilog/b13_C.v:3.230-3.234" *)
  output U417;
  (* src = "./verilog/b13_C.v:3.236-3.240" *)
  output U450;
  (* src = "./verilog/b13_C.v:3.242-3.246" *)
  output U451;
  (* src = "./verilog/b13_C.v:3.248-3.252" *)
  output U452;
  (* src = "./verilog/b13_C.v:3.254-3.258" *)
  output U453;
  (* src = "./verilog/b13_C.v:3.260-3.264" *)
  output U454;
  (* src = "./verilog/b13_C.v:3.266-3.270" *)
  output U455;
  (* src = "./verilog/b13_C.v:3.272-3.276" *)
  output U456;
  (* src = "./verilog/b13_C.v:3.278-3.282" *)
  output U457;
  (* src = "./verilog/b13_C.v:3.284-3.288" *)
  output U458;
  (* src = "./verilog/b13_C.v:3.290-3.294" *)
  output U459;
  (* src = "./verilog/b13_C.v:3.296-3.300" *)
  output U460;
  (* src = "./verilog/b13_C.v:3.302-3.306" *)
  output U461;
  (* src = "./verilog/b13_C.v:3.308-3.312" *)
  output U462;
  (* src = "./verilog/b13_C.v:3.314-3.318" *)
  output U463;
  (* src = "./verilog/b13_C.v:3.320-3.324" *)
  output U464;
  NOT _433_ (
    .A(_197_),
    .Y(_269_)
  );
  NOT _434_ (
    .A(_159_),
    .Y(_270_)
  );
  NOT _435_ (
    .A(_179_),
    .Y(_271_)
  );
  NOT _436_ (
    .A(_175_),
    .Y(_272_)
  );
  NOT _437_ (
    .A(_176_),
    .Y(_273_)
  );
  NOT _438_ (
    .A(_201_),
    .Y(_274_)
  );
  NOT _439_ (
    .A(_200_),
    .Y(_275_)
  );
  NOT _440_ (
    .A(_195_),
    .Y(_276_)
  );
  NOT _441_ (
    .A(_204_),
    .Y(_277_)
  );
  NOT _442_ (
    .A(_181_),
    .Y(_278_)
  );
  NOT _443_ (
    .A(_182_),
    .Y(_279_)
  );
  NOT _444_ (
    .A(_183_),
    .Y(_280_)
  );
  NOT _445_ (
    .A(_215_),
    .Y(_281_)
  );
  AND _446_ (
    .A(_269_),
    .B(_198_),
    .Y(_282_)
  );
  AND _447_ (
    .A(_159_),
    .B(_282_),
    .Y(_283_)
  );
  NAND _448_ (
    .A(_159_),
    .B(_282_),
    .Y(_284_)
  );
  NAND _449_ (
    .A(_179_),
    .B(_283_),
    .Y(_285_)
  );
  NAND _450_ (
    .A(_193_),
    .B(_285_),
    .Y(_286_)
  );
  NOR _451_ (
    .A(_197_),
    .B(_198_),
    .Y(_287_)
  );
  NAND _452_ (
    .A(_199_),
    .B(_287_),
    .Y(_288_)
  );
  NAND _453_ (
    .A(_286_),
    .B(_288_),
    .Y(_221_)
  );
  NAND _454_ (
    .A(_272_),
    .B(_176_),
    .Y(_289_)
  );
  NAND _455_ (
    .A(_175_),
    .B(_273_),
    .Y(_290_)
  );
  NAND _456_ (
    .A(_274_),
    .B(_290_),
    .Y(_291_)
  );
  AND _457_ (
    .A(_289_),
    .B(_291_),
    .Y(_226_)
  );
  AND _458_ (
    .A(_214_),
    .B(_275_),
    .Y(_242_)
  );
  OR _459_ (
    .A(_194_),
    .B(_196_),
    .Y(_292_)
  );
  NOR _460_ (
    .A(_173_),
    .B(_195_),
    .Y(_293_)
  );
  OR _461_ (
    .A(_173_),
    .B(_195_),
    .Y(_294_)
  );
  OR _462_ (
    .A(_193_),
    .B(_196_),
    .Y(_295_)
  );
  AND _463_ (
    .A(_294_),
    .B(_295_),
    .Y(_296_)
  );
  OR _464_ (
    .A(_195_),
    .B(_196_),
    .Y(_297_)
  );
  AND _465_ (
    .A(_194_),
    .B(_297_),
    .Y(_298_)
  );
  NAND _466_ (
    .A(_296_),
    .B(_298_),
    .Y(_299_)
  );
  AND _467_ (
    .A(_292_),
    .B(_299_),
    .Y(_268_)
  );
  AND _468_ (
    .A(_178_),
    .B(_277_),
    .Y(_300_)
  );
  NAND _469_ (
    .A(_178_),
    .B(_277_),
    .Y(_301_)
  );
  NAND _470_ (
    .A(_164_),
    .B(_300_),
    .Y(_302_)
  );
  NAND _471_ (
    .A(_185_),
    .B(_301_),
    .Y(_303_)
  );
  NAND _472_ (
    .A(_302_),
    .B(_303_),
    .Y(_264_)
  );
  AND _473_ (
    .A(_275_),
    .B(_213_),
    .Y(_241_)
  );
  NAND _474_ (
    .A(_270_),
    .B(_282_),
    .Y(_304_)
  );
  NAND _475_ (
    .A(_202_),
    .B(_304_),
    .Y(_305_)
  );
  OR _476_ (
    .A(_269_),
    .B(_198_),
    .Y(_306_)
  );
  NAND _477_ (
    .A(_305_),
    .B(_306_),
    .Y(_223_)
  );
  NAND _478_ (
    .A(_284_),
    .B(_288_),
    .Y(_218_)
  );
  OR _479_ (
    .A(_205_),
    .B(_206_),
    .Y(_307_)
  );
  OR _480_ (
    .A(_207_),
    .B(_307_),
    .Y(_308_)
  );
  AND _481_ (
    .A(_208_),
    .B(_308_),
    .Y(_309_)
  );
  OR _482_ (
    .A(_209_),
    .B(_309_),
    .Y(_310_)
  );
  AND _483_ (
    .A(_210_),
    .B(_211_),
    .Y(_311_)
  );
  NAND _484_ (
    .A(_310_),
    .B(_311_),
    .Y(_312_)
  );
  OR _485_ (
    .A(_212_),
    .B(_213_),
    .Y(_313_)
  );
  NOR _486_ (
    .A(_214_),
    .B(_313_),
    .Y(_314_)
  );
  NAND _487_ (
    .A(_312_),
    .B(_314_),
    .Y(_315_)
  );
  NAND _488_ (
    .A(_200_),
    .B(_315_),
    .Y(_316_)
  );
  AND _489_ (
    .A(_200_),
    .B(_205_),
    .Y(_317_)
  );
  XOR _490_ (
    .A(_200_),
    .B(_205_),
    .Y(_318_)
  );
  AND _491_ (
    .A(_316_),
    .B(_318_),
    .Y(_233_)
  );
  NAND _492_ (
    .A(_165_),
    .B(_300_),
    .Y(_319_)
  );
  NAND _493_ (
    .A(_186_),
    .B(_301_),
    .Y(_320_)
  );
  NAND _494_ (
    .A(_319_),
    .B(_320_),
    .Y(_263_)
  );
  NAND _495_ (
    .A(_166_),
    .B(_300_),
    .Y(_321_)
  );
  NAND _496_ (
    .A(_187_),
    .B(_301_),
    .Y(_322_)
  );
  NAND _497_ (
    .A(_321_),
    .B(_322_),
    .Y(_262_)
  );
  NAND _498_ (
    .A(_167_),
    .B(_300_),
    .Y(_323_)
  );
  NAND _499_ (
    .A(_188_),
    .B(_301_),
    .Y(_324_)
  );
  NAND _500_ (
    .A(_323_),
    .B(_324_),
    .Y(_261_)
  );
  NAND _501_ (
    .A(_168_),
    .B(_300_),
    .Y(_325_)
  );
  NAND _502_ (
    .A(_189_),
    .B(_301_),
    .Y(_326_)
  );
  NAND _503_ (
    .A(_325_),
    .B(_326_),
    .Y(_260_)
  );
  NOR _504_ (
    .A(_278_),
    .B(_316_),
    .Y(_327_)
  );
  OR _505_ (
    .A(_278_),
    .B(_316_),
    .Y(_328_)
  );
  NAND _506_ (
    .A(_182_),
    .B(_328_),
    .Y(_329_)
  );
  NOR _507_ (
    .A(_184_),
    .B(_183_),
    .Y(_330_)
  );
  OR _508_ (
    .A(_181_),
    .B(_330_),
    .Y(_331_)
  );
  AND _509_ (
    .A(_279_),
    .B(_183_),
    .Y(_332_)
  );
  NAND _510_ (
    .A(_279_),
    .B(_183_),
    .Y(_333_)
  );
  NAND _511_ (
    .A(_181_),
    .B(_333_),
    .Y(_334_)
  );
  NAND _512_ (
    .A(_331_),
    .B(_334_),
    .Y(_335_)
  );
  OR _513_ (
    .A(_316_),
    .B(_335_),
    .Y(_336_)
  );
  NAND _514_ (
    .A(_329_),
    .B(_336_),
    .Y(_243_)
  );
  NAND _515_ (
    .A(_169_),
    .B(_300_),
    .Y(_337_)
  );
  NAND _516_ (
    .A(_190_),
    .B(_301_),
    .Y(_338_)
  );
  NAND _517_ (
    .A(_337_),
    .B(_338_),
    .Y(_259_)
  );
  NAND _518_ (
    .A(_170_),
    .B(_300_),
    .Y(_339_)
  );
  NAND _519_ (
    .A(_191_),
    .B(_301_),
    .Y(_340_)
  );
  NAND _520_ (
    .A(_339_),
    .B(_340_),
    .Y(_258_)
  );
  NAND _521_ (
    .A(_171_),
    .B(_300_),
    .Y(_341_)
  );
  NAND _522_ (
    .A(_192_),
    .B(_301_),
    .Y(_342_)
  );
  NAND _523_ (
    .A(_341_),
    .B(_342_),
    .Y(_257_)
  );
  AND _524_ (
    .A(_201_),
    .B(_204_),
    .Y(_343_)
  );
  NAND _525_ (
    .A(_172_),
    .B(_343_),
    .Y(_344_)
  );
  OR _526_ (
    .A(_178_),
    .B(_174_),
    .Y(_345_)
  );
  NAND _527_ (
    .A(_301_),
    .B(_345_),
    .Y(_346_)
  );
  NAND _528_ (
    .A(_274_),
    .B(_346_),
    .Y(_347_)
  );
  AND _529_ (
    .A(_344_),
    .B(_347_),
    .Y(_255_)
  );
  NOR _530_ (
    .A(_194_),
    .B(_276_),
    .Y(_348_)
  );
  AND _531_ (
    .A(_196_),
    .B(_348_),
    .Y(_349_)
  );
  NAND _532_ (
    .A(_196_),
    .B(_348_),
    .Y(_350_)
  );
  AND _533_ (
    .A(_161_),
    .B(_160_),
    .Y(_351_)
  );
  XOR _534_ (
    .A(_161_),
    .B(_160_),
    .Y(_352_)
  );
  NAND _535_ (
    .A(_349_),
    .B(_352_),
    .Y(_353_)
  );
  NAND _536_ (
    .A(_156_),
    .B(_350_),
    .Y(_354_)
  );
  NAND _537_ (
    .A(_353_),
    .B(_354_),
    .Y(_250_)
  );
  OR _538_ (
    .A(_203_),
    .B(_348_),
    .Y(_355_)
  );
  AND _539_ (
    .A(_350_),
    .B(_355_),
    .Y(_254_)
  );
  AND _540_ (
    .A(_194_),
    .B(_195_),
    .Y(_356_)
  );
  NAND _541_ (
    .A(_193_),
    .B(_356_),
    .Y(_357_)
  );
  NAND _542_ (
    .A(_199_),
    .B(_357_),
    .Y(_358_)
  );
  NAND _543_ (
    .A(_196_),
    .B(_356_),
    .Y(_359_)
  );
  NAND _544_ (
    .A(_358_),
    .B(_359_),
    .Y(_231_)
  );
  NAND _545_ (
    .A(_159_),
    .B(_271_),
    .Y(_360_)
  );
  AND _546_ (
    .A(_271_),
    .B(_283_),
    .Y(_361_)
  );
  XOR _547_ (
    .A(_179_),
    .B(_283_),
    .Y(_225_)
  );
  AND _548_ (
    .A(_206_),
    .B(_317_),
    .Y(_362_)
  );
  AND _549_ (
    .A(_207_),
    .B(_362_),
    .Y(_363_)
  );
  AND _550_ (
    .A(_208_),
    .B(_363_),
    .Y(_364_)
  );
  AND _551_ (
    .A(_209_),
    .B(_364_),
    .Y(_365_)
  );
  XOR _552_ (
    .A(_209_),
    .B(_364_),
    .Y(_366_)
  );
  AND _553_ (
    .A(_316_),
    .B(_366_),
    .Y(_237_)
  );
  NAND _554_ (
    .A(_162_),
    .B(_351_),
    .Y(_367_)
  );
  AND _555_ (
    .A(_349_),
    .B(_367_),
    .Y(_368_)
  );
  NAND _556_ (
    .A(_163_),
    .B(_368_),
    .Y(_369_)
  );
  NAND _557_ (
    .A(_158_),
    .B(_350_),
    .Y(_370_)
  );
  NAND _558_ (
    .A(_369_),
    .B(_370_),
    .Y(_252_)
  );
  AND _559_ (
    .A(_194_),
    .B(_196_),
    .Y(_371_)
  );
  OR _560_ (
    .A(_348_),
    .B(_371_),
    .Y(_219_)
  );
  NAND _561_ (
    .A(_190_),
    .B(_332_),
    .Y(_372_)
  );
  AND _562_ (
    .A(_182_),
    .B(_183_),
    .Y(_373_)
  );
  NAND _563_ (
    .A(_188_),
    .B(_373_),
    .Y(_374_)
  );
  AND _564_ (
    .A(_372_),
    .B(_374_),
    .Y(_375_)
  );
  AND _565_ (
    .A(_182_),
    .B(_280_),
    .Y(_376_)
  );
  NAND _566_ (
    .A(_192_),
    .B(_376_),
    .Y(_377_)
  );
  NAND _567_ (
    .A(_186_),
    .B(_184_),
    .Y(_378_)
  );
  AND _568_ (
    .A(_278_),
    .B(_378_),
    .Y(_379_)
  );
  AND _569_ (
    .A(_377_),
    .B(_379_),
    .Y(_380_)
  );
  NAND _570_ (
    .A(_375_),
    .B(_380_),
    .Y(_381_)
  );
  NAND _571_ (
    .A(_279_),
    .B(_330_),
    .Y(_382_)
  );
  NAND _572_ (
    .A(_185_),
    .B(_184_),
    .Y(_383_)
  );
  AND _573_ (
    .A(_181_),
    .B(_383_),
    .Y(_384_)
  );
  AND _574_ (
    .A(_382_),
    .B(_384_),
    .Y(_385_)
  );
  NAND _575_ (
    .A(_187_),
    .B(_373_),
    .Y(_386_)
  );
  NAND _576_ (
    .A(_189_),
    .B(_332_),
    .Y(_387_)
  );
  NAND _577_ (
    .A(_191_),
    .B(_376_),
    .Y(_388_)
  );
  AND _578_ (
    .A(_387_),
    .B(_388_),
    .Y(_389_)
  );
  AND _579_ (
    .A(_386_),
    .B(_389_),
    .Y(_390_)
  );
  NAND _580_ (
    .A(_385_),
    .B(_390_),
    .Y(_391_)
  );
  AND _581_ (
    .A(_381_),
    .B(_391_),
    .Y(_392_)
  );
  OR _582_ (
    .A(_316_),
    .B(_392_),
    .Y(_216_)
  );
  NAND _583_ (
    .A(_293_),
    .B(_371_),
    .Y(_393_)
  );
  NAND _584_ (
    .A(_180_),
    .B(_393_),
    .Y(_394_)
  );
  OR _585_ (
    .A(_194_),
    .B(_297_),
    .Y(_395_)
  );
  NAND _586_ (
    .A(_394_),
    .B(_395_),
    .Y(_229_)
  );
  NAND _587_ (
    .A(_175_),
    .B(_215_),
    .Y(_396_)
  );
  NAND _588_ (
    .A(_176_),
    .B(_396_),
    .Y(_397_)
  );
  NAND _589_ (
    .A(_290_),
    .B(_397_),
    .Y(_256_)
  );
  AND _590_ (
    .A(_160_),
    .B(_349_),
    .Y(_398_)
  );
  XOR _591_ (
    .A(_160_),
    .B(_349_),
    .Y(_246_)
  );
  AND _592_ (
    .A(_349_),
    .B(_351_),
    .Y(_399_)
  );
  XOR _593_ (
    .A(_161_),
    .B(_398_),
    .Y(_247_)
  );
  OR _594_ (
    .A(_162_),
    .B(_351_),
    .Y(_400_)
  );
  NAND _595_ (
    .A(_368_),
    .B(_400_),
    .Y(_401_)
  );
  XOR _596_ (
    .A(_162_),
    .B(_399_),
    .Y(_248_)
  );
  NAND _597_ (
    .A(_173_),
    .B(_276_),
    .Y(_402_)
  );
  NAND _598_ (
    .A(_295_),
    .B(_402_),
    .Y(_403_)
  );
  NAND _599_ (
    .A(_297_),
    .B(_403_),
    .Y(_404_)
  );
  NAND _600_ (
    .A(_194_),
    .B(_404_),
    .Y(_220_)
  );
  NOR _601_ (
    .A(_155_),
    .B(_349_),
    .Y(_405_)
  );
  NOR _602_ (
    .A(_398_),
    .B(_405_),
    .Y(_249_)
  );
  NAND _603_ (
    .A(_184_),
    .B(_328_),
    .Y(_406_)
  );
  NAND _604_ (
    .A(_327_),
    .B(_373_),
    .Y(_407_)
  );
  NAND _605_ (
    .A(_406_),
    .B(_407_),
    .Y(_265_)
  );
  AND _606_ (
    .A(_210_),
    .B(_365_),
    .Y(_408_)
  );
  OR _607_ (
    .A(_211_),
    .B(_408_),
    .Y(_409_)
  );
  AND _608_ (
    .A(_316_),
    .B(_409_),
    .Y(_239_)
  );
  XOR _609_ (
    .A(_207_),
    .B(_362_),
    .Y(_410_)
  );
  AND _610_ (
    .A(_316_),
    .B(_410_),
    .Y(_235_)
  );
  NAND _611_ (
    .A(_157_),
    .B(_350_),
    .Y(_411_)
  );
  NAND _612_ (
    .A(_401_),
    .B(_411_),
    .Y(_251_)
  );
  NAND _613_ (
    .A(_280_),
    .B(_328_),
    .Y(_412_)
  );
  OR _614_ (
    .A(_328_),
    .B(_376_),
    .Y(_413_)
  );
  NAND _615_ (
    .A(_412_),
    .B(_413_),
    .Y(_414_)
  );
  NAND _616_ (
    .A(_333_),
    .B(_414_),
    .Y(_244_)
  );
  XOR _617_ (
    .A(_208_),
    .B(_363_),
    .Y(_415_)
  );
  AND _618_ (
    .A(_316_),
    .B(_415_),
    .Y(_236_)
  );
  XOR _619_ (
    .A(_210_),
    .B(_365_),
    .Y(_416_)
  );
  AND _620_ (
    .A(_316_),
    .B(_416_),
    .Y(_238_)
  );
  OR _621_ (
    .A(_278_),
    .B(_184_),
    .Y(_417_)
  );
  AND _622_ (
    .A(_382_),
    .B(_417_),
    .Y(_418_)
  );
  OR _623_ (
    .A(_316_),
    .B(_418_),
    .Y(_419_)
  );
  NAND _624_ (
    .A(_278_),
    .B(_316_),
    .Y(_420_)
  );
  AND _625_ (
    .A(_419_),
    .B(_420_),
    .Y(_266_)
  );
  NAND _626_ (
    .A(_159_),
    .B(_175_),
    .Y(_421_)
  );
  NAND _627_ (
    .A(_273_),
    .B(_421_),
    .Y(_422_)
  );
  NAND _628_ (
    .A(_270_),
    .B(_396_),
    .Y(_423_)
  );
  AND _629_ (
    .A(_422_),
    .B(_423_),
    .Y(_224_)
  );
  NAND _630_ (
    .A(_272_),
    .B(_202_),
    .Y(_424_)
  );
  AND _631_ (
    .A(_273_),
    .B(_202_),
    .Y(_425_)
  );
  OR _632_ (
    .A(_178_),
    .B(_425_),
    .Y(_426_)
  );
  AND _633_ (
    .A(_290_),
    .B(_426_),
    .Y(_232_)
  );
  AND _634_ (
    .A(_275_),
    .B(_212_),
    .Y(_240_)
  );
  NAND _635_ (
    .A(_282_),
    .B(_360_),
    .Y(_427_)
  );
  NAND _636_ (
    .A(_306_),
    .B(_427_),
    .Y(_267_)
  );
  NAND _637_ (
    .A(_200_),
    .B(_281_),
    .Y(_428_)
  );
  NAND _638_ (
    .A(_344_),
    .B(_428_),
    .Y(_230_)
  );
  NAND _639_ (
    .A(_397_),
    .B(_424_),
    .Y(_245_)
  );
  NAND _640_ (
    .A(_177_),
    .B(_350_),
    .Y(_429_)
  );
  NAND _641_ (
    .A(_393_),
    .B(_429_),
    .Y(_227_)
  );
  XOR _642_ (
    .A(_206_),
    .B(_317_),
    .Y(_430_)
  );
  AND _643_ (
    .A(_316_),
    .B(_430_),
    .Y(_234_)
  );
  NOR _644_ (
    .A(_328_),
    .B(_382_),
    .Y(_217_)
  );
  OR _645_ (
    .A(_350_),
    .B(_367_),
    .Y(_431_)
  );
  AND _646_ (
    .A(_163_),
    .B(_431_),
    .Y(_253_)
  );
  NOR _647_ (
    .A(_178_),
    .B(_204_),
    .Y(_432_)
  );
  NAND _648_ (
    .A(_281_),
    .B(_432_),
    .Y(_228_)
  );
  OR _649_ (
    .A(_154_),
    .B(_361_),
    .Y(_222_)
  );
  assign _197_ = S2_REG_0__SCAN_IN;
  assign _198_ = S2_REG_1__SCAN_IN;
  assign _199_ = SEND_DATA_REG_SCAN_IN;
  assign _159_ = CONFIRM_REG_SCAN_IN;
  assign _179_ = MPX_REG_SCAN_IN;
  assign _193_ = RDY_REG_SCAN_IN;
  assign U385 = _221_;
  assign _175_ = ITFC_STATE_REG_0__SCAN_IN;
  assign _176_ = ITFC_STATE_REG_1__SCAN_IN;
  assign _201_ = SEND_REG_SCAN_IN;
  assign U390 = _226_;
  assign _214_ = TX_CONTA_REG_9__SCAN_IN;
  assign _200_ = SEND_EN_REG_SCAN_IN;
  assign _209_ = TX_CONTA_REG_4__SCAN_IN;
  assign _205_ = TX_CONTA_REG_0__SCAN_IN;
  assign _206_ = TX_CONTA_REG_1__SCAN_IN;
  assign _207_ = TX_CONTA_REG_2__SCAN_IN;
  assign _208_ = TX_CONTA_REG_3__SCAN_IN;
  assign _210_ = TX_CONTA_REG_5__SCAN_IN;
  assign _211_ = TX_CONTA_REG_6__SCAN_IN;
  assign _212_ = TX_CONTA_REG_7__SCAN_IN;
  assign _213_ = TX_CONTA_REG_8__SCAN_IN;
  assign U406 = _242_;
  assign _194_ = S1_REG_0__SCAN_IN;
  assign _173_ = EOC;
  assign _195_ = S1_REG_1__SCAN_IN;
  assign _196_ = S1_REG_2__SCAN_IN;
  assign U464 = _268_;
  assign _178_ = LOAD_REG_SCAN_IN;
  assign _204_ = TRE_REG_SCAN_IN;
  assign _185_ = OUT_REG_REG_0__SCAN_IN;
  assign _164_ = DATA_IN_0_;
  assign U460 = _264_;
  assign U405 = _241_;
  assign _202_ = SHOT_REG_SCAN_IN;
  assign U387 = _223_;
  assign U382 = _218_;
  assign U397 = _233_;
  assign _186_ = OUT_REG_REG_1__SCAN_IN;
  assign _165_ = DATA_IN_1_;
  assign U459 = _263_;
  assign _187_ = OUT_REG_REG_2__SCAN_IN;
  assign _166_ = DATA_IN_2_;
  assign U458 = _262_;
  assign _188_ = OUT_REG_REG_3__SCAN_IN;
  assign _167_ = DATA_IN_3_;
  assign U457 = _261_;
  assign _189_ = OUT_REG_REG_4__SCAN_IN;
  assign _168_ = DATA_IN_4_;
  assign U456 = _260_;
  assign _181_ = NEXT_BIT_REG_0__SCAN_IN;
  assign _182_ = NEXT_BIT_REG_1__SCAN_IN;
  assign _184_ = NEXT_BIT_REG_3__SCAN_IN;
  assign _183_ = NEXT_BIT_REG_2__SCAN_IN;
  assign U407 = _243_;
  assign _190_ = OUT_REG_REG_5__SCAN_IN;
  assign _169_ = DATA_IN_5_;
  assign U455 = _259_;
  assign _191_ = OUT_REG_REG_6__SCAN_IN;
  assign _170_ = DATA_IN_6_;
  assign U454 = _258_;
  assign _192_ = OUT_REG_REG_7__SCAN_IN;
  assign _171_ = DATA_IN_7_;
  assign U453 = _257_;
  assign _174_ = ERROR_REG_SCAN_IN;
  assign _172_ = DSR;
  assign U451 = _255_;
  assign _156_ = CANALE_REG_1__SCAN_IN;
  assign _161_ = CONTA_TMP_REG_1__SCAN_IN;
  assign _160_ = CONTA_TMP_REG_0__SCAN_IN;
  assign _162_ = CONTA_TMP_REG_2__SCAN_IN;
  assign U414 = _250_;
  assign _203_ = SOC_REG_SCAN_IN;
  assign U450 = _254_;
  assign U395 = _231_;
  assign U389 = _225_;
  assign U401 = _237_;
  assign _158_ = CANALE_REG_3__SCAN_IN;
  assign _163_ = CONTA_TMP_REG_3__SCAN_IN;
  assign U416 = _252_;
  assign U383 = _219_;
  assign U380 = _216_;
  assign _180_ = MUX_EN_REG_SCAN_IN;
  assign U393 = _229_;
  assign _215_ = TX_END_REG_SCAN_IN;
  assign U452 = _256_;
  assign U410 = _246_;
  assign U411 = _247_;
  assign U412 = _248_;
  assign U384 = _220_;
  assign _155_ = CANALE_REG_0__SCAN_IN;
  assign U413 = _249_;
  assign U461 = _265_;
  assign U403 = _239_;
  assign U399 = _235_;
  assign _157_ = CANALE_REG_2__SCAN_IN;
  assign U415 = _251_;
  assign U408 = _244_;
  assign U400 = _236_;
  assign U402 = _238_;
  assign U462 = _266_;
  assign U388 = _224_;
  assign U396 = _232_;
  assign U404 = _240_;
  assign U463 = _267_;
  assign U394 = _230_;
  assign U409 = _245_;
  assign _177_ = LOAD_DATO_REG_SCAN_IN;
  assign U391 = _227_;
  assign U398 = _234_;
  assign U381 = _217_;
  assign U417 = _253_;
  assign U392 = _228_;
  assign _154_ = ADD_MPX2_REG_SCAN_IN;
  assign U386 = _222_;
endmodule
